name: dockerfile

on:
  workflow_dispatch:
    inputs:
      pywhlobf_version:
        description: 'pywhlobf version'
        required: true
      publish:
        description: 'yes/no'
        default: 'no'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform_tag:
          # manylinux1.
          - "manylinux1_x86_64"
          - "manylinux1_i686"

          # manylinux2010.
          - "manylinux2010_x86_64"
          - "manylinux2010_i686"

          # manylinux2014.
          - "manylinux2014_x86_64"
          - "manylinux2014_i686"
          # TODO:
          # - "manylinux2014_aarch64"
          # - "manylinux2014_ppc64le"
          # - "manylinux2014_s390x"

          # manylinux_2_24.
          - "manylinux_2_24_x86_64"
          - "manylinux_2_24_i686"
          # TODO:
          # - "manylinux_2_24_aarch64"
          # - "manylinux_2_24_ppc64le"
          # - "manylinux_2_24_s390x"
        cython3:
          - "no"
          - "yes"

    steps:
      - uses: actions/checkout@v2
      - name: checkout
        uses: actions/upload-artifact@v1
        with:
          name: checkout
          path: .
      - name: Build and push.
        run: |
          cd dockerfile

          if [ "${{ matrix.cython3 }}" = 'no' ] ; then
            TAG="${{ github.event.inputs.pywhlobf_version }}-${{ matrix.platform_tag }}"
          elif  [ "${{ matrix.cython3 }}" = 'yes' ] ; then
            TAG="${{ github.event.inputs.pywhlobf_version }}-cython3-${{ matrix.platform_tag }}"
          else
            exit 1

          docker build \
            --build-arg PLATFORM_TAG="${{ matrix.platform_tag }}" \
            --build-arg PYWHLOBF_PLATFORM_TAG="${{ matrix.platform_tag }}" \
            --build-arg PYWHLOBF_CYTHON3="${{ matrix.cython3 }}" \
            --build-arg PYWHLOBF_VERSION="${{ github.event.inputs.pywhlobf_version }}" \
            -t pywhlobf/pywhlobf:"$TAG" \
            .

          if [ "${{ github.event.inputs.publish }}" = 'yes' ] ; then
            docker login --username=pywhlobf --password=${{ secrets.DOCKER_PASSWORD }}
            docker push pywhlobf/pywhlobf:"$TAG"

            docker login \
              --username="${{ secrets.HUAWEICLOUD_AREA }}@${{ secrets.HUAWEICLOUD_AK }}" \
              --password=${{ secrets.HUAWEICLOUD_TOKEN }} \
              "swr.${{ secrets.HUAWEICLOUD_AREA }}.myhuaweicloud.com"
            docker tag pywhlobf/pywhlobf:"$TAG" swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/pywhlobf/pywhlobf:"$TAG"
            docker push swr."${{ secrets.HUAWEICLOUD_AREA }}".myhuaweicloud.com/pywhlobf/pywhlobf:"$TAG"
          else
            echo 'not publish'
          fi
