name: dockerfile

on:
  workflow_dispatch:
    inputs:
      pywhlobf_version:
        description: 'pywhlobf version'
        required: true
      publish:
        description: 'yes/no'
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform_tag:
          - "manylinux1_x86_64"
          - "manylinux1_i686"
          - "manylinux2010_x86_64"
          - "manylinux2010_i686"
          - "manylinux2014_x86_64"
          - "manylinux2014_i686"
          # - "manylinux2014_aarch64"
          # - "manylinux2014_ppc64le"
          # - "manylinux2014_s390x"
    steps:
      - uses: actions/checkout@v2
      - name: Upload checkout
        uses: actions/upload-artifact@v1
        with:
          name: checkout
          path: .
      - name: Build and push.
        run: |
          cd dockerfile
          TAG="${{ github.event.inputs.pywhlobf_version }}-${{ matrix.platform_tag }}"
          docker build \
            --build-arg PLATFORM_TAG="${{ matrix.platform_tag }}" \
            --build-arg PYWHLOBF_PLATFORM_TAG="${{ matrix.platform_tag }}" \
            --build-arg PYWHLOBF_VERSION="${{ github.event.inputs.pywhlobf_version }}" \
            -t pywhlobf/pywhlobf:"$TAG" \
            .

          if [ "${{ github.event.inputs.publish }}" -eq 'yes' ] ; then
            echo 'todo'
          else
            echo 'not publish'
          fi
